config/routes.rb
Rails.application.routes.draw do
  resources :pokedexes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokedex.rb
class Pokedex < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokedexes_controller.rb
class PokedexesController < ApplicationController
  before_action :set_pokedex, only: %i[ show edit update destroy ]

  # GET /pokedexes or /pokedexes.json
  def index
    @pokedexes = Pokedex.all
  end

  # GET /pokedexes/1 or /pokedexes/1.json
  def show
  end

  # GET /pokedexes/new
  def new
    @pokedex = Pokedex.new
  end

  # GET /pokedexes/1/edit
  def edit
  end

  # POST /pokedexes or /pokedexes.json
  def create
    @pokedex = Pokedex.new(pokedex_params)

    respond_to do |format|
      if @pokedex.save
        format.html { redirect_to pokedex_url(@pokedex), notice: "Pokedex was successfully created." }
        format.json { render :show, status: :created, location: @pokedex }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pokedex.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokedexes/1 or /pokedexes/1.json
  def update
    respond_to do |format|
      if @pokedex.update(pokedex_params)
        format.html { redirect_to pokedex_url(@pokedex), notice: "Pokedex was successfully updated." }
        format.json { render :show, status: :ok, location: @pokedex }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pokedex.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokedexes/1 or /pokedexes/1.json
  def destroy
    @pokedex.destroy

    respond_to do |format|
      format.html { redirect_to pokedexes_url, notice: "Pokedex was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokedex
      @pokedex = Pokedex.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokedex_params
      params.require(:pokedex).permit(:name, :element)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokedexes_helper.rb
module PokedexesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokemon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokedexes/_form.html.erb
<%= form_with(model: pokedex) do |form| %>
  <% if pokedex.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pokedex.errors.count, "error") %> prohibited this pokedex from being saved:</h2>

      <ul>
        <% pokedex.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :element, style: "display: block" %>
    <%= form.text_field :element %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pokedexes/_pokedex.html.erb
<div id="<%= dom_id pokedex %>">
  <p>
    <strong>Name:</strong>
    <%= pokedex.name %>
  </p>

  <p>
    <strong>Element:</strong>
    <%= pokedex.element %>
  </p>

</div>

app/views/pokedexes/edit.html.erb
<h1>Editing pokedex</h1>

<%= render "form", pokedex: @pokedex %>

<br>

<div>
  <%= link_to "Show this pokedex", @pokedex %> |
  <%= link_to "Back to pokedexes", pokedexes_path %>
</div>

app/views/pokedexes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pokedexes</h1>

<div id="pokedexes">
  <% @pokedexes.each do |pokedex| %>
    <%= render pokedex %>
    <p>
      <%= link_to "Show this pokedex", pokedex %>
    </p>
  <% end %>
</div>

<%= link_to "New pokedex", new_pokedex_path %>

app/views/pokedexes/new.html.erb
<h1>New pokedex</h1>

<%= render "form", pokedex: @pokedex %>

<br>

<div>
  <%= link_to "Back to pokedexes", pokedexes_path %>
</div>

app/views/pokedexes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pokedex %>

<div>
  <%= link_to "Edit this pokedex", edit_pokedex_path(@pokedex) %> |
  <%= link_to "Back to pokedexes", pokedexes_path %>

  <%= button_to "Destroy this pokedex", @pokedex, method: :delete %>
</div>